# -*- coding: utf-8 -*-
"""P04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDvUdd4QG6NGAws_QpuStWq5t5BDF5WF

**Cutomer Behavior Analysis**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import squarify # A library for creating treemaps

df = pd.read_csv('/content/drive/MyDrive/refine_file.csv')
df.head()

"""Analysing Costumer Behavior using **RFM** Method

In this RFM method we need three things for analysing customer behavior first Recency, Frequecy and Monetary
"""

# Convert 'InvoiceDate' to datetime objects
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], format='%d-%m-%Y %H:%M')
# Calculate Recency for each customer: the number of days since their last purchase
# Define the analysis date as the day after the last invoice date in the dataset
day = df['InvoiceDate'].max() + pd.Timedelta(days=1)
# Calculate the difference in days between the analysis date and each customer's last purchase date
recency = df.groupby('Customer ID')['InvoiceDate'].max().apply(lambda x: (day - x).days)
# Display the Recency for the first 10 customers
display(recency.head())

# Calculate Frequency for each customer: the total number of purchases made by each customer
frequency = df.groupby('Customer ID')['InvoiceDate'].count()
# Display the Frequency for the first 10 customers
frequency.head()

# Calculate Monetary value for each customer: the total revenue generated from each customer's purchases
monetary = df.groupby('Customer ID')['Revenue'].sum()
# Display the Monetary value for the first 10 customers
monetary.head()

# Create a new DataFrame 'rfm' to store the calculated Recency, Frequency, and Monetary values for each customer
rfm = pd.DataFrame({'Recency':recency,'Frequency':frequency,'Monetary':monetary})
# Display the first 10 rows of the RFM DataFrame
rfm.head(10)

# Scoring customers based on RFM values by dividing them into 5 quantiles (quintiles)
# Assign R_Score: 5 for most recent, 1 for least recent
rfm['R_Score'] = pd.qcut(rfm['Recency'], 5, labels=[5,4, 3, 2, 1])
# Assign F_Score: 1 for least frequent, 5 for most frequent
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1, 2, 3, 4,5])
# Assign M_Score: 1 for lowest monetary value, 5 for highest monetary value
rfm['M_Score'] = pd.qcut(rfm['Monetary'], 5, labels=[1, 2, 3, 4,5])

# Combine the individual RFM scores into a single string to represent the RFM segment score
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

# disply
rfm.head()

# Using a dictionary for clear, non-overlapping segment mapping
segment_map = {
    r'[1-2][1-2]': 'Hibernating',
    r'[1-2][3-4]': 'At Risk',
    r'[1-2]5': 'Can\'t Lose Them',
    r'3[1-2]': 'About to Sleep',
    r'33': 'Need Attention',
    r'[3-4][4-5]': 'Loyal Customers',
    r'41': 'Promising',
    r'51': 'New Customers',
    r'[4-5][2-3]': 'Potential Loyalists',
    r'5[4-5]': 'Champions'
}

# Use regex to map RFM scores to segments
rfm['Segment'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str)
rfm['Segment'] = rfm['Segment'].replace(segment_map, regex=True)

# Display the count of customers in each segment
print("Customer Segment Distribution:")
print(rfm['Segment'].value_counts())

# Bussiness Actions
# Define business actions for each segment
business_actions = {
    "Hibernating": "Re-engage with reminder emails, seasonal promotions, or limited-time discounts.",
    "Loyal Customers": "Strengthen relationship with exclusive offers, loyalty rewards, and early access to new products.",
    "Champions": "Reward with VIP programs, personalized gifts, and brand ambassador opportunities.",
    "At Risk": "Launch win-back campaigns, offer special discounts, and request feedback to understand disengagement.",
    "Potential Loyalists": "Nurture with targeted recommendations, onboarding offers, and membership incentives.",
    "About to Sleep": "Send wake-up campaigns, birthday/anniversary offers, or personalized coupons.",
    "Need Attention": "Use personalized outreach, highlight trending products, and send surveys to keep them active.",
    "Can't Lose Them": "Offer strong retention incentives, special appreciation messages, and reactivation bundles.",
    "Promising": "Encourage repeat purchases with targeted recommendations, cross-selling, and small perks.",
    "New Customer": "Deliver a strong onboarding experience, welcome discounts, and introduce best-sellers."
}

# Add the 'Action' column based on the 'Segment'
rfm["Action"] = rfm["Segment"].map(business_actions)

# Save the updated segmentation results
rfm.to_csv("customer_segments_with_actions.csv", index=False)

print("✅ Segmentation completed. File saved: customer_segments_with_actions.csv")

rfm.head()

#  Bar Chart for Segment Distribution
plt.figure(figsize=(12, 6))
sns.countplot(data=rfm, x='Segment', order=rfm['Segment'].value_counts().index, palette='viridis')
plt.title('Customer Segment Distribution')
plt.xlabel('Segment')
plt.ylabel('Number of Customers')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Scatter Plot for Recency vs. Frequency of 200 customers
plt.figure(figsize=(12, 8))
sns.scatterplot(data=rfm.head(200), x='Recency', y='Frequency', hue='Segment', palette='viridis', s=80, alpha=0.7)
plt.title('Recency vs. Frequency by Segment')
plt.xlabel('Recency (Days since last purchase)')
plt.ylabel('Frequency (Total purchases)')
plt.legend(title='Customer Segments')
plt.grid(True)
plt.show()

# Treemap for Segment Proportions
segment_counts = rfm['Segment'].value_counts()
plt.figure(figsize=(14, 9))
squarify.plot(sizes=segment_counts.values,
              label=[f'{label}\n({count})' for label, count in segment_counts.items()],
              color=sns.color_palette("viridis", len(segment_counts)),
              alpha=0.8)
plt.title('Treemap of Customer Segments')
plt.axis('off')
plt.show()