# -*- coding: utf-8 -*-
"""Multi-SKU Dynamic Pricing Model for Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqzoSZBd6E4Z2V9cV8xrTTbGICgxKr7M
"""

# ==============================================================================
# Multi-SKU Dynamic Pricing Model with Competitor Data
#
# To run this script in Google Colab:
# 1. Create a new Colab notebook.
# 2. In the left-hand pane, click the "Files" icon (folder icon).
# 3. Click the "Upload to session storage" button.
# 4. Upload your 'refine_file.csv' and 'competitor_prices.csv' files.
# 5. Copy and paste this entire script into a code cell and run it.
#
# This model will:
# - Identify your top 5 best-selling products.
# - Loop through each product, training a unique demand forecasting model.
# - Generate dynamic price recommendations for each one.
# - Present a final summary table with all recommendations.
# ==============================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error
import holidays
import random
import warnings

# Suppress harmless warnings
warnings.filterwarnings('ignore')

# --- 1. Setup and Reproducibility ---
print("--- Multi-SKU Dynamic Pricing Model ---")
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

# --- 2. Data Loading ---
try:
    df = pd.read_csv("refine_file.csv")
    competitor_df = pd.read_csv("competitor_prices.csv")
    print("Successfully loaded sales and competitor data.")
except FileNotFoundError as e:
    print(f"\nERROR: Could not find a required file: {e.filename}")
    print("Please make sure 'refine_file.csv' and 'competitor_prices.csv' are uploaded to your Colab session.")
    # Exit gracefully if data is missing
    exit()

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')

# --- 3. LSTM Model Architecture ---
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super(LSTMModel, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=0.2)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out, _ = self.lstm(x)
        out = self.fc(out[:, -1, :])
        return out

# --- 4. Dynamic Pricing Function ---
def calculate_dynamic_price(base_price, forecasted_demand, baseline_demand, elasticity=-1.5, intensity=0.1):
    if baseline_demand == 0: return base_price # Avoid division by zero
    demand_diff = (forecasted_demand - baseline_demand) / baseline_demand
    price_change_factor = (demand_diff / elasticity) * intensity
    new_price = base_price * (1 + price_change_factor)
    max_price, min_price = base_price * 1.25, base_price * 0.75
    return max(min(new_price, max_price), min_price)

# --- 5. Main Processing Loop for Each SKU ---
# Identify the top 5 selling products (SKUs)
top_5_products = df['StockCode'].value_counts().nlargest(5).index.tolist()
print(f"\nIdentified Top 5 Products for Analysis: {top_5_products}")

all_results = []

for product_id in top_5_products:
    print(f"\n{'='*60}\nProcessing Product (SKU): {product_id}\n{'='*60}")

    # --- A. Data Preparation for the current SKU ---
    product_df = df[df['StockCode'] == product_id].copy()
    daily_sales_df = product_df.resample('D', on='InvoiceDate')['Quantity'].sum().to_frame()

    # --- B. Feature Engineering ---
    daily_sales_df['day_of_week'] = daily_sales_df.index.dayofweek
    daily_sales_df['month'] = daily_sales_df.index.month
    daily_sales_df['lag_1_day'] = daily_sales_df['Quantity'].shift(1)
    daily_sales_df['lag_7_days'] = daily_sales_df['Quantity'].shift(7)
    daily_sales_df['rolling_mean_7'] = daily_sales_df['Quantity'].shift(1).rolling(window=7).mean()

    # Merge competitor prices
    product_competitor_prices = competitor_df[competitor_df['StockCode'] == product_id]
    if not product_competitor_prices.empty:
        for col in ['Competitor_A_Price', 'Competitor_B_Price', 'Competitor_C_Price']:
            daily_sales_df[col.lower()] = product_competitor_prices[col].iloc[0]

    daily_sales_df.fillna(0, inplace=True)

    # --- C. Scaling and Sequencing ---
    scaler = MinMaxScaler()
    scaled_features = scaler.fit_transform(daily_sales_df)
    target_col_idx = daily_sales_df.columns.get_loc("Quantity")
    seq_length = 30
    X, y = [], []
    for i in range(len(scaled_features) - seq_length):
        X.append(scaled_features[i:i + seq_length])
        y.append(scaled_features[i + seq_length, target_col_idx])
    X, y = np.array(X), np.array(y)

    if len(X) < 20: # Skip products with insufficient data
        print(f"Skipping {product_id} due to insufficient historical data.")
        continue

    # --- D. Data Splitting and DataLoader Creation ---
    train_size = int(len(X) * 0.8)
    X_train, y_train = X[:train_size], y[:train_size]
    X_test, y_test = X[train_size:], y[train_size:]

    X_train_tensor = torch.from_numpy(X_train).float()
    y_train_tensor = torch.from_numpy(y_train).float().view(-1, 1)
    X_test_tensor = torch.from_numpy(X_test).float()

    train_loader = DataLoader(TensorDataset(X_train_tensor, y_train_tensor), batch_size=32, shuffle=False)

    # --- E. Model Training for the SKU ---
    input_size = X_train.shape[2]
    model = LSTMModel(input_size=input_size, hidden_size=50, num_layers=2, output_size=1)
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.005)

    print(f"Training demand forecast model for {product_id}...")
    for epoch in range(50):
        for batch_X, batch_y in train_loader:
            outputs = model(batch_X)
            loss = criterion(outputs, batch_y)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    # --- F. Forecasting and Evaluation ---
    model.eval()
    with torch.no_grad():
        test_outputs = model(X_test_tensor)
    predictions_scaled = test_outputs.numpy().flatten()

    dummy_array = np.zeros((len(predictions_scaled), scaled_features.shape[1]))
    dummy_array[:, target_col_idx] = predictions_scaled
    forecasted_demand = scaler.inverse_transform(dummy_array)[:, target_col_idx]
    forecasted_demand = np.maximum(0, forecasted_demand) # Ensure demand is not negative

    mae = mean_absolute_error(y_test, scaler.inverse_transform(dummy_array)[:, target_col_idx])
    print(f"Forecast MAE for {product_id}: {mae:.2f}")

    # --- G. Dynamic Pricing Calculation ---
    BASE_PRICE = product_df['Price'].mean()
    BASELINE_DEMAND = daily_sales_df['Quantity'].mean()

    # We need to forecast for the next day. We'll use the last sequence from our data.
    last_sequence = torch.from_numpy(scaled_features[-seq_length:]).unsqueeze(0).float()
    with torch.no_grad():
        next_day_scaled_pred = model(last_sequence).item()

    dummy_pred = np.zeros((1, scaled_features.shape[1]))
    dummy_pred[:, target_col_idx] = next_day_scaled_pred
    next_day_forecast = scaler.inverse_transform(dummy_pred)[:, target_col_idx][0]
    next_day_forecast = max(0, next_day_forecast)

    suggested_price = calculate_dynamic_price(BASE_PRICE, next_day_forecast, BASELINE_DEMAND)

    # --- H. Store Results ---
    all_results.append({
        'StockCode': product_id,
        'Base_Price': round(BASE_PRICE, 2),
        'Avg_Daily_Demand': round(BASELINE_DEMAND, 2),
        'Forecasted_Demand_Next_Day': round(next_day_forecast, 2),
        'Suggested_Dynamic_Price': round(suggested_price, 2)
    })

# --- 6. Final Summary ---
print(f"\n{'='*60}\nDynamic Pricing Recommendations Summary\n{'='*60}")
if all_results:
    summary_df = pd.DataFrame(all_results)
    print(summary_df.to_string())
else:
    print("No results were generated. This might be due to insufficient data for the top products.")

# --- 7. Visualization of a Sample Product ---
if all_results:
    sample_product_id = summary_df['StockCode'].iloc[0]
    print(f"\n\nVisualizing forecast vs. actual for sample product: {sample_product_id}")

    # Re-running the forecast for the test period for plotting
    # (This is slightly redundant but good for a clear visual)
    product_df = df[df['StockCode'] == sample_product_id].copy()
    daily_sales_df = product_df.resample('D', on='InvoiceDate')['Quantity'].sum().to_frame()
    daily_sales_df.fillna(0, inplace=True)
    test_dates = daily_sales_df.index[-len(y_test):]

    # Getting actuals
    actual_demand_for_plot = daily_sales_df['Quantity'][-len(y_test):].values

    plt.figure(figsize=(15, 7))
    plt.plot(test_dates, actual_demand_for_plot, label='Actual Demand', color='blue', linestyle='--', alpha=0.7)
    plt.plot(test_dates, forecasted_demand, label='Forecasted Demand', color='red', linewidth=2)
    plt.title(f'Demand Forecast vs. Actuals for SKU: {sample_product_id}')
    plt.xlabel('Date')
    plt.ylabel('Quantity Sold')
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.show()